-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 08:56:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema admin_smartvillage
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `admin_smartvillage` ;

-- -----------------------------------------------------
-- Schema admin_smartvillage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admin_smartvillage` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `admin_smartvillage` ;

-- -----------------------------------------------------
-- Table `admin_smartvillage`.`data_barang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_smartvillage`.`data_barang` ;

CREATE TABLE IF NOT EXISTS `admin_smartvillage`.`data_barang` (
  `kode_barang` CHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `nama_barang` VARCHAR(30) NOT NULL,
  `harga_barang` INT NOT NULL,
  PRIMARY KEY (`kode_barang`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `admin_smartvillage`.`data_layanan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_smartvillage`.`data_layanan` ;

CREATE TABLE IF NOT EXISTS `admin_smartvillage`.`data_layanan` (
  `kode_layanan` CHAR(5) NOT NULL,
  `nama_layanan` VARCHAR(30) NOT NULL,
  `harga_layanan` INT NOT NULL,
  PRIMARY KEY (`kode_layanan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `admin_smartvillage`.`data_pelanggan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_smartvillage`.`data_pelanggan` ;

CREATE TABLE IF NOT EXISTS `admin_smartvillage`.`data_pelanggan` (
  `id_pelanggan` VARCHAR(64) NOT NULL,
  `nama_pelanggan` MEDIUMTEXT NOT NULL,
  `no_telp` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `alamat` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_pelanggan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `admin_smartvillage`.`data_traksaksi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_smartvillage`.`data_traksaksi` ;

CREATE TABLE IF NOT EXISTS `admin_smartvillage`.`data_traksaksi` (
  `id_transaksi` VARCHAR(64) NOT NULL,
  `nama_desa` VARCHAR(30) NOT NULL,
  `qty` INT NOT NULL,
  `total` INT NOT NULL,
  `id_pelanggan` CHAR(64) NOT NULL,
  PRIMARY KEY (`id_transaksi`),
  INDEX `id_pelanggan` (`id_pelanggan` ASC),
  CONSTRAINT `data_traksaksi_ibfk_2`
    FOREIGN KEY (`id_pelanggan`)
    REFERENCES `admin_smartvillage`.`data_pelanggan` (`id_pelanggan`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `admin_smartvillage`.`perjanjian_kerjasama`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_smartvillage`.`perjanjian_kerjasama` ;

CREATE TABLE IF NOT EXISTS `admin_smartvillage`.`perjanjian_kerjasama` (
  `id_perjanjian_kerjasama` VARCHAR(64) NOT NULL,
  `nama_desa` VARCHAR(30) NOT NULL,
  `nama_kades` MEDIUMTEXT NOT NULL,
  `tgl` DATE NOT NULL,
  `id_transaksi` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id_perjanjian_kerjasama`),
  INDEX `id_transaksi` (`id_transaksi` ASC),
  CONSTRAINT `perjanjian_kerjasama_ibfk_1`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `admin_smartvillage`.`data_traksaksi` (`id_transaksi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `admin_smartvillage`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_smartvillage`.`users` ;

CREATE TABLE IF NOT EXISTS `admin_smartvillage`.`users` (
  `id_user` VARCHAR(64) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `nama_lengkap` MEDIUMTEXT NOT NULL,
  `jabatan` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `no_telp` VARCHAR(20) NOT NULL,
  `alamat` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `admin_smartvillage`.`data_pesanan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_smartvillage`.`data_pesanan` ;

CREATE TABLE IF NOT EXISTS `admin_smartvillage`.`data_pesanan` (
  `id_pesanan` VARCHAR(64) NOT NULL,
  `id_transaksi` VARCHAR(64) NOT NULL,
  `kode_barang` CHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `kode_layanan` CHAR(5) NOT NULL,
  PRIMARY KEY (`id_pesanan`),
  INDEX `id_transaksi_idx` (`id_transaksi` ASC),
  INDEX `kode_barang_idx` (`kode_layanan` ASC),
  INDEX `fk_data_pesanan_data_barang1_idx` (`kode_barang` ASC),
  CONSTRAINT `id_transaksi`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `admin_smartvillage`.`data_traksaksi` (`id_transaksi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `kode_layanan`
    FOREIGN KEY (`kode_layanan`)
    REFERENCES `admin_smartvillage`.`data_layanan` (`kode_layanan`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_data_pesanan_data_barang1`
    FOREIGN KEY (`kode_barang`)
    REFERENCES `admin_smartvillage`.`data_barang` (`kode_barang`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
